"""Modelos ORM — espejo del modelo de datos del plan.

Dinero como Numeric(12, 2), nunca Float: los floats binarios acumulan errores
de redondeo (0.1 + 0.2 != 0.3), inaceptable en banca incluso mock.
"""
from datetime import datetime
from decimal import Decimal

from sqlalchemy import DateTime, ForeignKey, Identity, Numeric, String, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .database import Base


class Cliente(Base):
    __tablename__ = "clientes"

    # Identity(): en Oracle genera "GENERATED BY DEFAULT AS IDENTITY" (sin esto
    # Oracle NO autoincrementa y el INSERT falla con ORA-01400). SQLite lo
    # ignora y usa su autoincremento normal, así que los tests no cambian.
    id: Mapped[int] = mapped_column(Identity(), primary_key=True)
    nombre: Mapped[str] = mapped_column(String(80))
    apellido: Mapped[str] = mapped_column(String(80))
    email: Mapped[str] = mapped_column(String(120), unique=True, index=True)
    cedula: Mapped[str] = mapped_column(String(20), unique=True)
    password_hash: Mapped[str] = mapped_column(String(100))
    creado_en: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())

    cuentas: Mapped[list["Cuenta"]] = relationship(back_populates="cliente")


class Cuenta(Base):
    __tablename__ = "cuentas"

    # Identity(): en Oracle genera "GENERATED BY DEFAULT AS IDENTITY" (sin esto
    # Oracle NO autoincrementa y el INSERT falla con ORA-01400). SQLite lo
    # ignora y usa su autoincremento normal, así que los tests no cambian.
    id: Mapped[int] = mapped_column(Identity(), primary_key=True)
    cliente_id: Mapped[int] = mapped_column(ForeignKey("clientes.id"), index=True)
    numero_cuenta: Mapped[str] = mapped_column(String(20), unique=True, index=True)
    tipo: Mapped[str] = mapped_column(String(10))  # AHORRO | CORRIENTE
    saldo: Mapped[Decimal] = mapped_column(Numeric(12, 2), default=Decimal("0"))
    moneda: Mapped[str] = mapped_column(String(3), default="USD")
    estado: Mapped[str] = mapped_column(String(10), default="ACTIVA")
    creado_en: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())

    cliente: Mapped[Cliente] = relationship(back_populates="cuentas")
    movimientos: Mapped[list["Movimiento"]] = relationship(back_populates="cuenta")


class Movimiento(Base):
    __tablename__ = "movimientos"

    # Identity(): en Oracle genera "GENERATED BY DEFAULT AS IDENTITY" (sin esto
    # Oracle NO autoincrementa y el INSERT falla con ORA-01400). SQLite lo
    # ignora y usa su autoincremento normal, así que los tests no cambian.
    id: Mapped[int] = mapped_column(Identity(), primary_key=True)
    cuenta_id: Mapped[int] = mapped_column(ForeignKey("cuentas.id"), index=True)
    tipo: Mapped[str] = mapped_column(String(10))  # DEBITO | CREDITO
    monto: Mapped[Decimal] = mapped_column(Numeric(12, 2))
    saldo_resultante: Mapped[Decimal] = mapped_column(Numeric(12, 2))
    descripcion: Mapped[str] = mapped_column(String(200))
    referencia: Mapped[str] = mapped_column(String(40), index=True)
    fecha: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())

    cuenta: Mapped[Cuenta] = relationship(back_populates="movimientos")


class Transferencia(Base):
    __tablename__ = "transferencias"

    # Identity(): en Oracle genera "GENERATED BY DEFAULT AS IDENTITY" (sin esto
    # Oracle NO autoincrementa y el INSERT falla con ORA-01400). SQLite lo
    # ignora y usa su autoincremento normal, así que los tests no cambian.
    id: Mapped[int] = mapped_column(Identity(), primary_key=True)
    cuenta_origen_id: Mapped[int] = mapped_column(ForeignKey("cuentas.id"))
    cuenta_destino_id: Mapped[int] = mapped_column(ForeignKey("cuentas.id"))
    monto: Mapped[Decimal] = mapped_column(Numeric(12, 2))
    estado: Mapped[str] = mapped_column(String(12))  # COMPLETADA | FALLIDA
    referencia: Mapped[str] = mapped_column(String(40), unique=True)
    fecha: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
